#!/usr/bin/env bash

script_dir=$(cd $(dirname $BASH_SOURCE[0]) && pwd)

XDG_CONFIG_HOME="$HOME/.config"
SCRIPTS="$HOME/.local/scripts"

log() {
  printf '[DEBUG] %s\n' "$*"
}

cpdirs() {
 local from="$1"
 local to="$2"

 pushd $script_dir/$from >/dev/null

 dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
 for dir in $dirs; do
   dir=${dir#*/}
   log "------------------$dir------------------"
   log "[executing] rm -rf $to/$dir"
   rm -rf "$to/$dir"

   log "[executing] cp -r $script_dir/$from/$dir $to/$dir"
   cp -r "$script_dir/$from/$dir" "$to/$dir"
 done

 popd >/dev/null
}

cpfiles(){
 local from="$1"
 local to="$2"
  
 pushd $script_dir/$from >/dev/null

 files=$(find . -mindepth 1 -maxdepth 1 -type f -executable)
 for file in $files; do 
   filename=${file#*/}
   log "------------------[scripts]${filename}------------------"
   log "[executing] rm $to/$filename"
   rm "$to/$filename" 2>/dev/null

   log "[executing] cp $script_dir/$from/$filename $to/$filename"
   cp "$script_dir/$from/$filename" "$to/$filename"
 done

 popd >/dev/null
}

cpdirs ".config" "$XDG_CONFIG_HOME"
cpfiles ".local/scripts" "$SCRIPTS"
